### PR TITLE
Rebuild for OpenSSL 3 and cleanup [skip ci]

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
This PR is a rebuild for OpenSSL 3. I also took the occasion to remove the unnecessary python variants from the build.

Note that I initially wanted to do a full cleanup of the dependencies, but I changed my mind and created a Jira ticket instead: https://anaconda.atlassian.net/browse/PKG-2177.

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM but we need a more experienced eye

**Review by ELundby45 — APPROVED** [review]
@JeanChristopheMorinPerso  Looks good to me, but would it be possible to make sure `pyarrow` still builds and tests against this?

**Comment by JeanChristopheMorinPerso** [comment]
@ELundby45 I did try locally and it worked fine. Is that enough or you'd like me to actually trigger a real rebuild of pyarrow?

**Comment by ELundby45** [comment]
> @ELundby45 I did try locally and it worked fine. Is that enough or you'd like me to actually trigger a real rebuild of pyarrow?

That works for me.

**Pull request merged**
